# -*- coding: utf-8 -*-
"""l201203_lab_assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1byo-Eii4wfLLW_hjDnV5oS6HlMgYXTMX
"""

"""Simple implementation of Lists"""

items = ['box', 'car', 'toy']
items.append('cake')
print(items) 

items.insert(2, 'book')
print(items)

stuff = ['jacket', 'spoon']
items.extend(stuff)
print(items)

items.append('car')
count = items.count('car')
print(count)

index = items.index('jacket')
print(index)

items.remove('car')
print(items)

"""Simple implementation of Tuples"""

old_tp = (5, 20, 23)
print(old_tp) 

new_tp = tuple([2, 4, 6])
print(new_tp)  

print(old_tp[0])  
print(old_tp[-1]) 

x = (1, 2, 3, 4, 5)
print(x[2:5]) 

sum = old_tp + new_tp
print(sum)

"""Simple implementation of Dictionaries"""

uni = {'name': 'Fast', 'location': 'Lahore', 'Age': 21}
print(uni)  

student = dict(name='Abdul', age=30, major='Computer Science')
print(student)

print(uni['name'])

uni['location'] = 'Karachi'
print(uni) 

uni['Age'] = 22
print(uni)

del student['age']
print(student)  

studentX = student.pop('major')
print(student)   
print(studentX)

"""Simple implementation of Loops"""

my_list = ['phone', 'clothes', 'toothbrush']
for stuff in my_list:
    print(stuff)

for letter in "Foo bar":
    print(letter)

for num in range(1, 6):
    print(num)

my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}
for key, value in my_dict.items():
    print(key, value)

num = 1
while num <= 5:
    print(num)
    num += 1

"""Simple implementation of Functions"""

def tuple(n1, n2):
    return (n1, n2)

out_tuple = tuple(2, 3)
print(out_tuple)


def add_numbers(*args):
    result = 0
    for num in args:
        result += num
    return result

sum3 = add_numbers(10, 20, 30, 40, 50, 60)
print(sum3)